pipeline {
    stages {
        stage('stage') {
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    sh '''#!/busybox/sh
                    /kaniko/executor -c `pwd` --destination=${DOCKER_REPOSITORY}:${PREVIEW_VERSION}
                    '''
                }
            }
        }
    }
}
