pipeline {
    stages {
        stage('stage') {
            steps {
                container('kaniko') {
                    sh """#!/busybox/sh
                    /kaniko/executor -c `pwd` --destination=${DOCKER_REPOSITORY}:${PREVIEW_VERSION}
                    """
                }
            }
        }
    }
}
